# Generated by Django 6.0.6 on 2026-06-16 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('equipment_type', models.CharField(choices=[('AC', 'Climatiseur'), ('FR', 'Réfrigérateur'), ('EL', 'Équipement électrique')], default='AC', max_length=2, verbose_name='Type')),
                ('installation_date', models.DateField(verbose_name="Date d'installation")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='default', max_length=100, verbose_name='ID de session')),
                ('sender', models.CharField(choices=[('USER', 'Technicien'), ('AI', 'Assistant IA')], max_length=10, verbose_name='Expéditeur')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='assets.equipment', verbose_name='Équipement concerné')),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Maintenance préventive'), ('CORRECTIVE', 'Maintenance corrective'), ('URGENT', 'Intervention urgente')], default='PREVENTIVE', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échec')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(verbose_name="Description de l'intervention")),
                ('technician_name', models.CharField(max_length=100, verbose_name='Nom du technicien')),
                ('intervention_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'intervention")),
                ('duration_hours', models.FloatField(default=1.0, verbose_name='Durée (heures)')),
                ('parts_used', models.TextField(blank=True, verbose_name='Pièces utilisées')),
                ('notes', models.TextField(blank=True, verbose_name='Notes supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='assets.equipment', verbose_name='Équipement')),
            ],
            options={
                'verbose_name': 'Journal de maintenance',
                'verbose_name_plural': 'Journaux de maintenance',
                'ordering': ['-intervention_date'],
            },
        ),
    ]
